### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by andymac4182** [datalogic/xamarin-sdk-docs#1]
We are migrating our app from Windows Mobile to Android and react-native. Is there a chance you will be supporting react-native bindings in the future?

**Comment by codybrookshear** [comment]
Hi Andrew,
No plans to support react-native currently. Most customers have shown more interest in Xamarin so far, but thanks for letting us know you are interested. I'll share with the team.

Cody

**Comment by lopes-vincent** [comment]
Hi, 

The react-native support is still not planned ?
I'm also very interested about it.
