### ISSUE TITLE
App crash on AddReadListener

### ISSUE THREAD

**Issue by Hobbes1987** [datalogic/xamarin-sdk-docs#2]
Hi,

I'm currently developing and testing an app using Xamarin on the Joya Touch. 
I managed (using the examples) to get an activity actually scan barcodes.

But now i moved the implementation of the IReadListener to a simple class (service for IOC).
In this service i get a hold on to the Handle of the current active activity, and pass that to the Handle property which needs to be implemented when implementing IReadListener.

But as soon as i call AddReadListener(this), where 'this' is the IOC-Service, the app crashes without any exceptions raised in my c# code.

Question is, is it allowed to implement IReadListener on something else than a MainActivity? Or is this about to be supported in the future?

I need this 'cause i dont want my xamarin (android) app to be dependand on a specific scanner driver, but eventually use datalogic drivers if available.

**Comment by codybrookshear** [comment]
Hi,
Maybe you need to extend Java.Lang.Object?

I made a branch where I used a separate class (MyReadListener) that implements IReadListener:
https://github.com/datalogic/xamarin-samples/tree/AddReadListener/DecodeListener

Maybe that will be useful to take a look at. I realize it's not the exact IOC-Service pattern you are using though.
