### ISSUE TITLE
Incorrect location for <uses-library> in manifest

### ISSUE THREAD

**Issue by JAgostoni** [datalogic/xamarin-sdk-docs#3]
The Xamarin [quick start document](https://datalogic.github.io/xamarin/quick-start/) needs to be changed to ensure the <uses-library> tag is placed as a child (inside) the <application> node and not under the manifest node.

The app crashes on the latest beta firmware (as of this post) with the misplacement of the node.

**Comment by codybrookshear** [comment]
Thank you. I have corrected this issue. My apologies for taking so long to getting around to it.

- Cody
